const BREEDS = [
  { korean: '래브라도 리트리버', english: 'Labrador Retriever',     apiPath: 'retriever/labrador' },
  { korean: '골든 리트리버',     english: 'Golden Retriever',        apiPath: 'retriever/golden'   },
  { korean: '저먼 셰퍼드',       english: 'German Shepherd',         apiPath: 'germanshepherd'     },
  { korean: '프렌치 불독',       english: 'French Bulldog',          apiPath: 'bulldog/french'     },
  { korean: '잉글리시 불독',     english: 'English Bulldog',         apiPath: 'bulldog/english'    },
  { korean: '푸들',             english: 'Poodle',                  apiPath: 'poodle'             },
  { korean: '비글',             english: 'Beagle',                  apiPath: 'beagle'             },
  { korean: '로트와일러',        english: 'Rottweiler',              apiPath: 'rottweiler'         },
  { korean: '닥스훈트',         english: 'Dachshund',               apiPath: 'dachshund'          },
  { korean: '웰시 코기',        english: 'Welsh Corgi',             apiPath: 'corgi/pembroke'     },
  { korean: '요크셔 테리어',     english: 'Yorkshire Terrier',       apiPath: 'terrier/yorkshire'  },
  { korean: '복서',             english: 'Boxer',                   apiPath: 'boxer'              },
  { korean: '시베리안 허스키',   english: 'Siberian Husky',          apiPath: 'husky'              },
  { korean: '그레이트 데인',     english: 'Great Dane',              apiPath: 'dane/great'         },
  { korean: '도베르만',          english: 'Doberman',                apiPath: 'doberman'           },
  { korean: '시추',             english: 'Shih Tzu',                apiPath: 'shihtzu'            },
  { korean: '보스턴 테리어',     english: 'Boston Terrier',          apiPath: 'terrier/boston'     },
  { korean: '포메라니안',        english: 'Pomeranian',              apiPath: 'pomeranian'         },
  { korean: '하바네세',          english: 'Havanese',                apiPath: 'havanese'           },
  { korean: '셔틀랜드 십독',     english: 'Shetland Sheepdog',       apiPath: 'sheepdog/shetland'  },
  { korean: '보더 콜리',        english: 'Border Collie',           apiPath: 'collie/border'      },
  { korean: '말티즈',           english: 'Maltese',                 apiPath: 'maltese'            },
  { korean: '사모예드',          english: 'Samoyed',                 apiPath: 'samoyed'            },
  { korean: '코커 스패니얼',     english: 'Cocker Spaniel',          apiPath: 'spaniel/cocker'     },
  { korean: '치와와',           english: 'Chihuahua',               apiPath: 'chihuahua'          },
];
