const BREEDS = [
  { korean: '래브라도 리트리버', english: 'Labrador Retriever',   apiPath: 'retriever/labrador', wikiTitle: 'Labrador Retriever'     },
  { korean: '골든 리트리버',     english: 'Golden Retriever',      apiPath: 'retriever/golden',   wikiTitle: 'Golden Retriever'       },
  { korean: '저먼 셰퍼드',       english: 'German Shepherd',       apiPath: 'germanshepherd',     wikiTitle: 'German Shepherd'        },
  { korean: '프렌치 불독',       english: 'French Bulldog',        apiPath: 'bulldog/french',     wikiTitle: 'French Bulldog'         },
  { korean: '잉글리시 불독',     english: 'English Bulldog',       apiPath: 'bulldog/english',    wikiTitle: 'Bulldog'                },
  { korean: '푸들',             english: 'Poodle',                apiPath: 'poodle',             wikiTitle: 'Poodle'                 },
  { korean: '비글',             english: 'Beagle',                apiPath: 'beagle',             wikiTitle: 'Beagle'                 },
  { korean: '로트와일러',        english: 'Rottweiler',            apiPath: 'rottweiler',         wikiTitle: 'Rottweiler'             },
  { korean: '닥스훈트',         english: 'Dachshund',             apiPath: 'dachshund',          wikiTitle: 'Dachshund'              },
  { korean: '웰시 코기',        english: 'Welsh Corgi',           apiPath: 'corgi/pembroke',     wikiTitle: 'Pembroke Welsh Corgi'   },
  { korean: '요크셔 테리어',     english: 'Yorkshire Terrier',     apiPath: 'terrier/yorkshire',  wikiTitle: 'Yorkshire Terrier'      },
  { korean: '복서',             english: 'Boxer',                 apiPath: 'boxer',              wikiTitle: 'Boxer (dog)'            },
  { korean: '시베리안 허스키',   english: 'Siberian Husky',        apiPath: 'husky',              wikiTitle: 'Siberian Husky'         },
  { korean: '그레이트 데인',     english: 'Great Dane',            apiPath: 'dane/great',         wikiTitle: 'Great Dane'             },
  { korean: '도베르만',          english: 'Doberman',              apiPath: 'doberman',           wikiTitle: 'Dobermann'              },
  { korean: '시추',             english: 'Shih Tzu',              apiPath: 'shihtzu',            wikiTitle: 'Shih Tzu'               },
  { korean: '보스턴 테리어',     english: 'Boston Terrier',        apiPath: 'terrier/boston',     wikiTitle: 'Boston Terrier'         },
  { korean: '포메라니안',        english: 'Pomeranian',            apiPath: 'pomeranian',         wikiTitle: 'Pomeranian (dog)'       },
  { korean: '하바네세',          english: 'Havanese',              apiPath: 'havanese',           wikiTitle: 'Havanese dog'           },
  { korean: '셔틀랜드 십독',     english: 'Shetland Sheepdog',     apiPath: 'sheepdog/shetland',  wikiTitle: 'Shetland Sheepdog'      },
  { korean: '보더 콜리',        english: 'Border Collie',         apiPath: 'collie/border',      wikiTitle: 'Border Collie'          },
  { korean: '말티즈',           english: 'Maltese',               apiPath: 'maltese',            wikiTitle: 'Maltese dog'            },
  { korean: '사모예드',          english: 'Samoyed',               apiPath: 'samoyed',            wikiTitle: 'Samoyed (dog)'          },
  { korean: '코커 스패니얼',     english: 'Cocker Spaniel',        apiPath: 'spaniel/cocker',     wikiTitle: 'Cocker Spaniel'         },
  { korean: '치와와',           english: 'Chihuahua',             apiPath: 'chihuahua',          wikiTitle: 'Chihuahua (dog)'        },
];
